### ISSUE TITLE
Add UB event

### ISSUE THREAD

**Issue by Zdancewic** [vellvm/vellvm#100]
As a first step to dealing better with undefined behavior, poision, and undef, we need to model undefined behavior.

The idea is to extend the set of LLVM events with a new event UndefinedBehavior, that represents LLVM's notion of undefined behavior.  Examples include division by 0, storing to an undef address, branching on poison etc.

This event is similar to Failure, but we intend it to be semantically distinct: Failure is reserved for incompletenesses in our implementation (e.g. the semantics doesn't yet support the `invoke` instruction) and in cases where there cannot possibly be well-defined behavior (e.g. partiality of an arithmetic operation caused because the LLVM program is ill-typed).

We should adjust the semantics to use UndefinedBehavior everywhere that it is appropriate.

**Comment by bollu** [comment]
What is the model of UB that vellvm will be implementing? Is it the one described in "killing undef and spreading poison"? Or is this some other model of UB?

**Comment by Zdancewic** [comment]
We're still trying to figure out the best way to proceed with the semantics of `undef` and `poison` since the "real" LLVM semantics is inconsistent.  The model you mention is a likely (and desirable) candidate, but we're also aiming to engineer things so that we can pretty easily try out different models (and perhaps even formally compare them).  We may start with a more conservative semantics (i.e. one that justifies fewer optimizations as "correct") to start.
