### ISSUE TITLE
Audit the use of poison values

### ISSUE THREAD

**Issue by Zdancewic** [vellvm/vellvm#101]
We should audit the semantics to vet its use of `DVALUE_Poison`, which is generated in multiple places.  `DVALUE_Poison` should be propagated according to LLVM semantics.  [See the LLVM Reference.](https://llvm.org/docs/LangRef.html#poison-values).

The semantics should be adjusted to raise the UndefinedBehavior event when `DVALUE_Poison` is encountered in an effect-generating context: jumps, stores, etc.

**Comment by Chobbes** [comment]
So, I'm a bit confused about where poison *actually* results in UB.

For instance, we have been saying that branching on poison raises UB. However, in LangRef it seems like this is very much not the case.

"Additionally, undefined behavior occurs if a side effect depends on poison. This includes side effects that are control dependent on a poisoned branch."

So if branching on poison doesn't cause poisoned side effects, then the result isn't UB? For instance it's unclear to me what would happen if you branch on poison, but each branch is just a NOP. It sounds like that wouldn't be UB?

Similarly, if you branch on poison and each branch would happen to exhibit the exact same side effects whenever this happens... It sounds like that also might not be UB?

Thoughts?
