### ISSUE TITLE
readonly token support

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#12]
The following IR code:

`define void @dft16(float* nocapture %Y, float* nocapture readonly %X) #1 {
`

fails to parse with the error:

`Fatal error: exception Failure("Parsing error: line 13, column 57, token 'readonly'")
`

**Comment by Zdancewic** [comment]
The param_attr definition is in Ollvm_ast near line 80.  We need to fix up the parser in /ml/ollvm_parser.ml to handle the new PARAM_Attr definitions.

**Comment by vzaliva** [comment]
Interestingly, this attribute is undocumented: http://releases.llvm.org/3.8.0/docs/LangRef.html#paramattrs
