### ISSUE TITLE
compilation depenency problem with CFG.vo

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#121]
One problem I encounter every time I update Vellvm is the following: after `make clean` some `.vo` files are left:
```$ find . -name \*.vo                                          09:24:09
./coq/Transformations/Traversal.vo
```
And I have to remove them manually. Then doing clean compilation always fails like this:
```COQC coq/Transformations/Traversal.v
COQC coq/Numeric/Fappli_IEEE_extra.v
COQC coq/Dom.v
COQC coq/Numeric/Integers.v
File "./coq/Transformations/Traversal.v", line 8, characters 5-8:
Error: Unable to locate library CFG with prefix Vellvm.

Makefile:73: recipe for target 'coq/Transformations/Traversal.vo' failed
make[1]: *** [coq/Transformations/Traversal.vo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/lord/coq/vellvm/src'
Makefile:38: recipe for target 'all' failed
make: *** [all] Error 2
```
To fix that I need to do `make coq/CFG.vo`, and after this, I can proceed with regular `make`. I think there is some dependency problem in Makefile.

**Comment by Zdancewic** [comment]
I think that we fixed this issue by adding Traversal.v to the dependencies in the Makefile.

**Comment by vzaliva** [comment]
I just tested and the problem is fixed now. Thanks!
