### ISSUE TITLE
reads from uninitialized memory with size 0 types

### ISSUE THREAD

**Issue by Chobbes** [vellvm/vellvm#131]
According to LangRef you're supposed to get `undef` if you load a value from uninitialized memory.

```
the result is undefined if the value was not originally written using a store of the same type.
```

This seems reasonable, however LLVM also explicitly allows for allocations of size 0 (e.g., for size 0 arrays).

```
Allocating zero bytes is legal, but the returned pointer may not be unique.
```

These two facts put together are actually quite frustrating for our current memory model! Essentially we have a map from addresses to bytes, and those bytes can be `SUndef` if they're uninitialized. If you load while there are `SUndef` bytes, you get `undef`, and when you initialize the memory location you write something other than `SUndef` there. So far so good.

However, if, for instance, you have a structure with a size 0 field, e.g....

```
{ [0 x i32], i32 } 
```

Then presumably the first field would actually share an address with the second field. This aliasing means that if I write a value to the second field it would also affect the first field. If I `store` a value to the second field, and then `load` from the first field, I should still get `undef` according to LangRef, however with our memory model I would get an empty array back.

Another issue is that it's unclear how to initialize a size 0 address like this in the first place. For instance if I `alloca [0 x i32]` I should have to store an empty array to the address that I get before I can read a non-`undef` value from it.

Any thoughts on how we should handle this? This is a really painful pathological case that seems to make everything more complicated, but unfortunately it does come up in proofs that we need for Helix about the memory model.

**Comment by Zdancewic** [comment]
Good, tricky questions.  

For the `{[0 x i32], i32}` example, I'm not sure you would get Undef -- you have written to the location (via an alias) with the correct type.  If the struct were of type `{[0 x i32], i8*}` then the you would get Undef.

I think that `alloca [0 x i32]` allocates 0 bytes of storage space.  Semantically wouldn't this yield a pointer to an empty map?  Storing to the resulting pointer would result in Undefined Behavior and loading from the pointer would return Undef.    Does that sound right?

**Comment by Chobbes** [comment]
> For the {[0 x i32], i32} example, I'm not sure you would get Undef -- you have written to the location (via an alias) with the correct type. If the struct were of type {[0 x i32], i8*} then the you would get Undef.

This might be true, yes.

> I think that alloca [0 x i32] allocates 0 bytes of storage space. Semantically wouldn't this yield a pointer to an empty map? Storing to the resulting pointer would result in Undefined Behavior and loading from the pointer would return Undef. Does that sound right?

I am not sure, I think this program might be valid:

```
define i8 @main() {
    %p = alloca [0 x i32]
    store [0 x i32] [ ], [0 x i32]* %p
    ret i8 1
}
```

So, you get these weird phantom stores that exist just to make the read not `undef`. And it's a little extra silly because, of course, there's only one value for `undef` of type `[0 x i32]`.

**Comment by YaZko** [comment]
A silly admit depends on this issue, we should try to resolve it before any release.

**Comment by Chobbes** [comment]
That would probably be a good idea. We might want to have a meeting at some point... I think it's a pretty tricky little issue, which might involve some modest changes to how we represent memory.

I'm a little unclear on some of the issues discussed in the thread and how we *should* handle them. I think it's easy enough to come up with /a/ solution, but I'm not sure how to best find out how LLVM proper handles this (I mean... Maybe it just doesn't care, because it sort of doesn't matter).

With respect to the conversation about `{[0 x i32], i8*}` and `{[0 x i32], i32}`. Here's what LangRef says about `load`:

```
The location of memory pointed to is loaded. If the value being loaded is of scalar type then the number of bytes read does not exceed the minimum number of bytes needed to hold all bits of the type. For example, loading an i24 reads at most three bytes. When loading a value of a type like i20 with a size that is not an integral number of bytes, the result is undefined if the value was not originally written using a store of the same type. If the value being loaded is of aggregate type, the bytes that correspond to padding may be accessed but are ignored, because it is impossible to observe padding from the loaded aggregate value. If <pointer> is not a well-defined value, the behavior is undefined.
```

I feel like the wording here is pretty strange, and maybe I don't fully understand what they're trying to get across. Why do I care that at most 3 bytes are read to load an `i24`? That seems like an implementation detail, but maybe it's a guarantee that LLVM wants to make for some reason.

Regardless, from this it's very unclear to me how a store to the second field in these structures should affect the load of the `[0 x i32]`. Maybe it should be `undef` because it's a different type, but that statement might only be about scalar types that have non-integral numbers of bytes? But then what if I store an `i32` to `a[0]` where `a` is the array? Should a load to `i8*` still be `undef` because it's a different type and should the load of the `i32` be the value? I'm not really sure, and maybe it's just weird and inconsistent.

Another potential issue... I believe LLVM supports flexible array members.

```
This means that single-dimension ‘variable sized array’ addressing can be implemented in LLVM with a zero length array type. An implementation of ‘pascal style arrays’ in LLVM could use the type “{ i32, [0 x float]}”, for example.
```

I believe this only matters with `malloc` (which we don't really have), but you should be allowed to allocate more than the 4 bytes for the `i32` in this structure, and then the extra bytes allocated can be used for the `float` array. I believe `GEP` should handle this correctly as is. I guess loads and stores of type [0 x float] to this array should essentially be a noop, but the question is whether we want a load before a store to give `undef` (which sort of doesn't matter because there's only one possible value for undef?). But then you also have to allow for loads and stores to the variable length array... If I store to `a[i]` for some `i`, what should `load [0 x float] a` be? Should it always be `undef`, or should it yield a length 0 array? Does it depend on what `i` is?

The immediate impact of all of this is that `allocate_spec` is currently untrue in these size 0 cases:

```
    Record ext_memory (m1 : memory_stack) (a : addr) (τ : dtyp) (v : uvalue) (m2 : memory_stack) : Prop :=
      {
      new_lu  : read m2 a τ = inr v;
      old_lu  : forall a' τ', allocated a' m1 ->
                         no_overlap_dtyp a τ a' τ' ->
                         read m2 a' τ' = read m1 a' τ'
      }.

    Record allocate_spec (m1 : memory_stack) (τ : dtyp) (m2 : memory_stack) (a : addr) : Prop :=
      {
      was_fresh : ~ allocated a m1;
      is_allocated : ext_memory m1 a τ (UVALUE_Undef τ) m2
      }.
```

We wanted to say that if you load from freshly allocated memory, then you just get `undef`. With how our memory is defined, however, if you load an empty array, you'll always get an empty array. There will be no `SUndef` bytes in the memory, and the deserialize function won't even look at any bytes in the empty array case.

One possible solution might be to weaken this lemma for now, and give `new_lu` a predicate on the size of the type. I'm not sure if this would be a problem in Helix, but Helix shouldn't load any `undef` values, and also I believe shouldn't allocate size 0 arrays, so maybe it just doesn't matter.

Longer term for Vellvm, I have no idea what the solution should be. I think it's something that's underspecified in LangRef, and so I guess we just have to make a choice?

**Comment by Chobbes** [comment]
The easiest solution for this (currently) was just to modify `new_lu` in `allocate_spec` with a precondition that says you only read `undef` back if the size of the type is non-zero. This allowed me to get rid of the admits that Helix depended on. I'm not sure if it's the right solution in the long term, but I think we can close this issue for now.
