### ISSUE TITLE
Enforcing quiet NaN

### ISSUE THREAD

**Issue by zoickx** [vellvm/vellvm#132]
Floating-point operations in vellvm always make NaN results quiet. That is, even if all the inputs of a function are sNaN (signaling NaN), the resulting NaN is forced to be quiet (see [quiet_nan_64](https://github.com/vellvm/vellvm/blob/master/src/coq/Numeric/Floats.v#L122)).

This behavior does not seem to be the case in LLVM. The following C snippet (compiled with clang-7.1.0) can serve as an example:
```C
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

int
main()
{
    uint64_t quiet_NaN_i = 0x7FF8000000000000;
    uint64_t signaling_NaN_i = 0x7FF0000000000001;
    double quiet_NaN = *(double *) &quiet_NaN_i;
    double signaling_NaN = *(double *) &signaling_NaN_i;

    uint64_t x_i;
    double x;

    printf("This is a quiet NaN: %16.16lx. It is indeed %f.\n", quiet_NaN_i, quiet_NaN);
    printf("This is a signaling NaN: %16.16lx. It is indeed %f.\n", signaling_NaN_i, signaling_NaN);

    printf("x = %16.16lx * %16.16lx (i.e. x = sNaN * qNaN)\n", signaling_NaN_i, quiet_NaN_i);
    x = signaling_NaN * quiet_NaN;

    x_i = *(uint64_t *)&x;

    if (x_i == quiet_NaN_i)
        printf("x is a quiet NaN\n");
    else if (x_i == signaling_NaN_i)
        printf("x is a signaling NaN!\n");
    else
        printf("Unexpected. x = %f, different from both outputs", x);

    return (0);
}
```
This shows that `sNaN * qNaN = sNaN` in LLVM. In vellvm, `sNaN * qNaN = qNaN` (exact same values):
```Coq
Compute Floats.Float.mul
        (@B754_nan 53 1024 false 1 eq_refl)
        (@B754_nan 53 1024 false 2251799813685248 eq_refl).
(* = B754_nan 53 1024 true 2251799813685249 (Floats.quiet_nan_64_proof 1) *)
```

I was unable to find direct mentions of how this is "supposed" to work, neither in IEEE-754, nor in the LLVM reference manuals.

**Comment by zoickx** [comment]
Code taken (modified) from https://lists.llvm.org/pipermail/llvm-dev/2014-April/071699.html

**Comment by vzaliva** [comment]
fixed
