### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by andrew-wja** [vellvm/vellvm#156]
Hi,

The instructions in the README appear to no longer be correct w.r.t the installation of the necessary opam packages

```
$ opam --version
2.0.8
$ opam install coq-ext-lib coq-paco coq-flocq coq-ceres coq-mathcomp-ssreflect 
[ERROR] No package named coq-ext-lib found.
[ERROR] No package named coq-paco found.
[ERROR] No package named coq-flocq found.
[ERROR] No package named coq-ceres found.
[ERROR] No package named coq-mathcomp-ssreflect found.
```

**Comment by Zdancewic** [comment]
I suspect that this is because you need to add the coq repository to opam.  If you do `opam repo` it should look something like:
```
opam repo
[NOTE] These are the repositories in use by the current switch. Use '--all' to see all configured repositories.

<><> Repository configuration for switch 4.10.0+flambda <><><><><><><><><><>  🐫 
 1 coq-released https://coq.inria.fr/opam/released
 2 default      https://opam.ocaml.org
```

You can add the coq released repository by doing:
```
opam repo add coq-released https://coq.inria.fr/opam/released
```

See the instructions here: [https://coq.inria.fr/opam-using.html](url)

**Comment by andrew-wja** [comment]
Perfect, thank you! It's my first time working with Coq programmatically (rather than just using the GUI). It might be good to add this info to the readme just for the sake of completeness. Thanks again!
