### ISSUE TITLE
Pointer comparisons

### ISSUE THREAD

**Issue by Zdancewic** [vellvm/vellvm#159]
Vellvm currently supports on equality comparison of pointer typed values, but should allow others.  Doing so is a bit tricky because non-equality comparisons are somewhat like `ptrtoint` casts that (nondeterministically) constrain the behaviors of the memory model.  One possible way to implement the semantics would be to do the casts and then use integer comparison. But this makes comparison "effectful" from the point of view of the semantics. 

The type of `icmp` may not allow full itrees?  See [the code here.](https://github.com/vellvm/vellvm/blob/bba371f7f634e6f5c0bf4e5003eedc14384c6a16/src/coq/Semantics/DynamicValues.v#L1397)

**Comment by Chobbes** [comment]
Addressed in fa4df4cf.
