### ISSUE TITLE
For the dsss branch, exact dependency versions should be mentioned

### ISSUE THREAD

**Issue by jwiegley** [vellvm/vellvm#2]
I'm trying to build the current `dsss` branch, using `compcert` 3.0.1 and `paco` 1.2.7, but the bulid fails with:

```
COQC coq/Classes.v
COQC coq/Util.v
COQC coq/Ollvm_ast.v
COQC coq/Misc.v
COQC coq/AstLib.v
COQC coq/Dom.v
COQC coq/CFG.v
COQC coq/CFGProp.v
COQC coq/Effects.v
File "./coq/Effects.v", line 195, characters 23-29:
Error: The reference upaco2 was not found in the current environment.
make[1]: *** [Makefile:42: coq/Effects.vo] Error 1
```

Is this a missing dependency, or the wrong version of `paco`?

**Comment by liyishuai** [comment]
It works with paco 1.2.8. You can check the [Dockerfile](https://hub.docker.com/r/ysli/vellvm/~/dockerfile/) for installation process.

**Comment by jwiegley** [comment]
Thank you, rebuilding now.  I should have a Nix expression to commit to the repository soon if it works.

**Comment by Zdancewic** [comment]
The summer school material being developed in conjunction with Vellvm 
will not require Paco.  The content is under heavy active development, 
so I recommend that you wait until the DSSS official web pages announce 
the installation instructions for the course materials.

-- 
Steve Zdancewic
Professor, Dept. of Computer and Information Science
University of Pennsylvania
http://www.cis.upenn.edu/~stevez

**Comment by jwiegley** [comment]
@Zdancewic Will do, thank you for the notice!
