### ISSUE TITLE
show_exp needs improvements. Missing cases for literal expressions for aggregate data types.

### ISSUE THREAD

**Issue by Chobbes** [vellvm/vellvm#204]
- EXP_Array
- EXP_Vector
- EXP_Struct
- EXP_Packed_struct

**Comment by hanxic** [comment]
Implemented `EXP_Struct`, `EXP_Packed_struct`, `EXP_Array`, `EXP_Vector`, `OP_Conversion`, and add fast-math label to `OP_FBinop`. Things to do: fast-math currently lack of `contract`, `afn`, and `reassoc`, don't have `OP_ShuffleVector` implement, and don't have EXP_Cstring implement. Also would be great if someone can check my implementation

**Comment by hanxic** [comment]
Fixed some bugs. There is a bug in GetElementPtr. Will fix it tmr
