### ISSUE TITLE
Add support for i8 

### ISSUE THREAD

**Issue by Zdancewic** [vellvm/vellvm#24]
In the long run, we want to think about adding support for arbitrary bit width integers.  But for now, we should just add i8's in the same way as i1 and i64.

**Comment by Chobbes** [comment]
Notes for me. These are some things that I believe I need to look at:

- Section CONVERSIONS.
  + looks like conversions between types
  + this might be something worth abstracting at some point
- Anything with DVALUE_I*
  + memory.v: some serializations, GEP stuff, and mem_step
  + DynamicValues.v
     * is_DVALUE_I8
     * eval_i8_op
     * coerce_integer_to_int
     * eval_iop_integer_h, integer_op
     * eval_i8_icmp, eval_icmp
  + DecidableEquality.v

Anything else come to mind?
