### ISSUE TITLE
Memory model bugs

### ISSUE THREAD

**Issue by nsobotka** [vellvm/vellvm#245]
Test files in tests/cis341 produce the following errors. 

slowsort, another_io_test, and bubble_sort throw "Read from memory with invalid provenance" errors.

insertion throws "Undefined behavior: reading from unallocated memory". 

All of these files have the correct output when run through clang.

**Comment by Chobbes** [comment]
Thanks!

There's a couple of possibilities:

1. The test cases could be doing wrong things, like accessing unallocated memory, or reading memory it shouldn't from a pointer.
2. The memory model implementation is wrong, and telling you that valid operations are invalid :).

I suspect that this issue might have something to do with the handling of global arrays. I think it should be fine --- there's `allocate_globals` and `initialize_globals` functions in `TopLevel.v` which *should* trigger the proper allocations and stores... But maybe there's something goofy there.

Try to figure out if you can cause these issues on smaller programs, or maybe narrow down exactly which `load` is causing the problem in the programs if you can.

**Notes on the error messages you're seeing:**

They're mostly what they sound like. Reading from memory with invalid provenance is supposed to mean that you have taken a pointer and somehow gotten a pointer to another region of memory that it's not allowed to access... And reading from unallocated memory is what it sounds like.

**Comment by Chobbes** [comment]
@nsobotka whenever you get an error message, you should copy and paste the full thing by the way.

I believe the provenance error message should print out more helpful information. Please run the tests and paste the full error messages here!

**Comment by nsobotka** [comment]
another_io_test: `Fatal error: exception Failure("Undefined Behaviour: Read from memory with invalid provenance -- addr: 8, addr prov: Some [], memory allocation id: \"Some 2\" memory: [(0,\"Some 1\"); (1,\"Some 1\"); (2,\"Some 1\"); (3,\"Some 1\"); (4,\"Some 1\"); (5,\"Some 1\"); (6,\"Some 1\"); (7,\"Some 1\"); (8,\"Some 2\"); (9,\"Some 2\"); (10,\"Some 2\"); (11,\"Some 2\"); (12,\"Some 2\"); (13,\"Some 2\"); (14,\"Some 2\"); (15,\"Some 2\"); (16,\"Some 3\"); (17,\"Some 3\"); (18,\"Some 3\"); (19,\"Some 3\"); (20,\"Some 3\"); (21,\"Some 3\"); (22,\"Some 3\"); (23,\"Some 3\"); (24,\"Some 3\"); (25,\"Some 3\"); (26,\"Some 3\"); (27,\"Some 3\"); (28,\"Some 3\"); (29,\"Some 3\"); (30,\"Some 3\"); (31,\"Some 3\"); (32,\"Some 3\"); (33,\"Some 3\"); (34,\"Some 3\"); (35,\"Some 3\"); (36,\"Some 3\"); (37,\"Some 3\"); (38,\"Some 3\"); (39,\"Some 3\"); (40,\"Some 3\"); (41,\"Some 3\"); (42,\"Some 3\"); (43,\"Some 3\"); (44,\"Some 3\"); (45,\"Some 3\"); (46,\"Some 3\"); (47,\"Some 3\"); (48,\"Some 3\"); (49,\"Some 3\"); (50,\"Some 3\"); (51,\"Some 3\"); (52,\"Some 3\"); (53,\"Some 3\"); (54,\"Some 3\"); (55,\"Some 3\"); (56,\"Some 3\"); (57,\"Some 3\"); (58,\"Some 3\"); (59,\"Some 3\"); (60,\"Some 3\"); (61,\"Some 3\"); (62,\"Some 3\"); (63,\"Some 3\"); (64,\"Some 3\"); (65,\"Some 4\"); (66,\"Some 4\"); (67,\"Some 4\"); (68,\"Some 4\"); (69,\"Some 4\"); (70,\"Some 5\"); (71,\"Some 5\"); (72,\"Some 5\"); (73,\"Some 5\"); (74,\"Some 5\"); (75,\"Some 5\"); (76,\"Some 5\"); (77,\"Some 5\")]")`

**Comment by nsobotka** [comment]
slowsort: `Fatal error: exception Failure("Undefined Behaviour: Read from memory with invalid provenance -- addr: 280, addr prov: Some [5], memory allocation id: \"Some 6\" memory: [(0,\"Some 1\"); (1,\"Some 1\"); (2,\"Some 1\"); (3,\"Some 1\"); (4,\"Some 1\"); (5,\"Some 1\"); (6,\"Some 1\"); (7,\"Some 1\"); (8,\"Some 2\"); (9,\"Some 2\"); (10,\"Some 2\"); (11,\"Some 2\"); (12,\"Some 2\"); (13,\"Some 2\"); (14,\"Some 2\"); ` (truncated)

**Comment by nsobotka** [comment]
bubble sort: `Fatal error: exception Failure("Undefined Behaviour: Read from memory with invalid provenance -- addr: 64, addr prov: Some [3], memory allocation id: \"Some 4\" memory: [(0,\"Some 1\"); (1,\"Some 1\"); (2,\"Some 1\"); (3,\"Some 1\"); (4,\"Some 1\"); (5,\"Some 1\"); (6,\"Some 1\"); (7,\"Some 1\"); (8,\"Some 2\"); (9,\"Some 2\"); (10,\"Some 2\"); (11,\"Some 2\"); (12,\"Some 2\"); (13,\"Some 2\"); (14,\"Some 2\"); (15,\"Some 2\"); (16,\"Some 3\"); (17,\"Some 3\"); (18,\"Some 3\"); (19,\"Some 3\"); (20,\"Some 3\"); (21,\"Some 3\"); (22,\"Some 3\"); (23,\"Some 3\"); (24,\"Some 3\"); (25,\"Some 3\"); (26,\"Some 3\"); (27,\"Some 3\"); (28,\"Some 3\"); (29,\"Some 3\"); (30,\"Some 3\"); (31,\"Some 3\"); (32,\"Some 3\"); (33,\"Some 3\"); (34,\"Some 3\"); (35,\"Some 3\"); (36,\"Some 3\"); (37,\"Some 3\"); (38,\"Some 3\"); (39,\"Some 3\"); (40,\"Some 3\"); (41,\"Some 3\"); (42,\"Some 3\"); (43,\"Some 3\"); (44,\"Some 3\"); (45,\"Some 3\"); (46,\"Some 3\"); (47,\"Some 3\"); (48,\"Some 3\"); (49,\"Some 3\"); (50,\"Some 3\"); (51,\"Some 3\"); (52,\"Some 3\"); (53,\"Some 3\"); (54,\"Some 3\"); (55,\"Some 3\"); (56,\"Some 3\"); (57,\"Some 3\"); (58,\"Some 3\"); (59,\"Some 3\"); (60,\"Some 3\"); (61,\"Some 3\"); (62,\"Some 3\"); (63,\"Some 3\"); (64,\"Some 4\"); (65,\"Some 4\"); (66,\"Some 4\"); (67,\"Some 4\"); (68,\"Some 4\"); (69,\"Some 4\"); (70,\"Some 4\"); (71,\"Some 4\"); (72,\"Some 5\"); (73,\"Some 5\"); (74,\"Some 5\"); (75,\"Some 5\"); (76,\"Some 5\"); (77,\"Some 5\"); (78,\"Some 5\"); (79,\"Some 5\")]")`

insertion: `Fatal error: exception Failure("Undefined Behaviour: Reading from unallocated memory.")`

**Comment by Chobbes** [comment]
Ah, I think `another_io_test` is illuminating. It takes in arguments from the command line using `argv`... And pulls out a pointer to the second string in `argv` using `getelementptr`. We actually always set this address for `argv` to `null` which has the `nil_provenance` so it can't access anything. I think this program does legitimate execute UB because it's not checking the size of `argv` with `argc` first.

**Comment by nsobotka** [comment]
I noticed that for `another_io_test` but `slowsort` doesn't make use of the inputs and still has the same error. Unless you're saying that this is the intended execution?

**Comment by Chobbes** [comment]
So, I'm looking at `bubblesort.ll` right now, and I'm noticing that it seems to be trying to access 1 byte after the third thing allocated in memory. The first 2 things allocated in memory are the 2 function pointers. Then the next thing is a 48 byte array.

So the problem is that it's trying to access one byte after the end of a 48-byte array. This is almost certainly a bug in the program. I suspect it is the same for all of the sorting algorithms.

In the case of `bubblesort.ll`...

```
  %left_indx = load i64, i64* %j
  %right_indx = add i64 %left_indx, 1
  %left = getelementptr [6 x i64], [6 x i64]* %list, i64 0, i64 %left_indx
  %right = getelementptr [6 x i64], [6 x i64]* %list, i64 0, i64 %right_indx
```

I notice that the `%right_indx` is `%left_indx + 1`, but `%left_index` is `%j`, which can be as high as `5`. If this is the case it will mean `%right_index` can equal `6`, which means `%right` goes off the end of the array and this load:

```
  %right_el = load i64, i64* %right
```

Is undefined behaviour.

I suspect all of the sorting algorithms share similar code, and are probably buggy in the same fashion. It'd be good to confirm that, though!

**Comment by Chobbes** [comment]
@nsobotka this issue can be closed, right?

**Comment by nsobotka** [comment]
Yep! This is all sorted out, all just problems with the test cases.
