### ISSUE TITLE
Implement printf

### ISSUE THREAD

**Issue by Chobbes** [vellvm/vellvm#298]

**Comment by Zdancewic** [comment]
The best way to implement `printf` is probably to:
1. implement `puts`
2. add support for the llvm `vararg` constructs
3. implement, by hand, a crafted version of `printf` in C that uses only constructs our semantics supports
4. compile the C code to LLVM, use our frontend to reify that LLVM as LLVMAst
5. write an intrinsic handler that uses that LLVM code as the semantics for the call

**Comment by Chobbes** [comment]
I believe a duplicate of this issue exists here: https://github.com/DeepSpec/InteractionTrees/issues/268

This is also related to issue #41 for vararg support. Implementing varargs should just be a matter of implementing these intrinsics:

https://llvm.org/docs/LangRef.html#variable-argument-handling-intrinsics

`va_start / va_copy / va_end` seem to be somewhat poorly documented, and I believe there were many potential cases for UB with them, but a simple handling of them is probably fine for now!

**Comment by Chobbes** [comment]
May need to think about how to handle `printf` as a library function and *not* an intrinsic.

If `printf` is an intrinsic, then we will have to do refinement proofs about `printf`. It might make sense to inject the printf declaration at the AST level, after parsing. May make sense to write a simple linker to combine two lists of TLE's. If one TLE has an external declaration and the other has a definition of that declaration we can add the definition at the start and remove the external declaration in the combined AST.

Using this we should be able to avoid doing proofs about functions like `printf` directly.

**Comment by rogerburtonpatel** [comment]
Once the parser is reviewed and in place, the last steps will be to build in a linker for the current best `printf.ll` and test with the coq implementation against sample programs that call `printf`. I'll try writing some now.

**Comment by Chobbes** [comment]
Implemented in ade4752
