### ISSUE TITLE
Bitcast to correct type bug

### ISSUE THREAD

**Issue by hanxic** [vellvm/vellvm#301]
Sometimes we encounter situations like 
`temporary_vellvm.ll:14:19: error: invalid cast opcode for cast from '<3 x float>' to '<1 x double>'
    %v5 = bitcast <3 x float> %v4 to <1 x double>`
Need to make sure that the type is more accurate

**Comment by Chobbes** [comment]
May be fixed by #300 / #305. Closing this issue for now, though there may still be problems because the bitcast generator currently generates some UB programs for other reasons.
