### ISSUE TITLE
Nix build fails with not finding path to QuickChick

### ISSUE THREAD

**Issue by ahmedshakill** [vellvm/vellvm#309]
builder for '/nix/store/cn7wcxglfhz7lgn9igh473p26vvbmmjd-coq8.15-vellvm-dev.drv' failed with exit code 2;
       last 10 log lines:
       > Warning: Cannot open ../lib/QuickChick/src/ [cannot-open-path,filesystem]
       > File "./coq/Numeric/IEEE754_extra.v", line 35, characters 21-22:
       > Error: The reference Z was not found in the current environment.
       >
       > make[2]: *** [Makefile:120: coq/Numeric/IEEE754_extra.vo] Error 1
       > make[2]: Leaving directory '/build/3m8061y50vmda9cy3kqd6snd7p3gsxvm-source/src'
       > make[1]: *** [Makefile:78: coq] Error 2
       > make[1]: Leaving directory '/build/3m8061y50vmda9cy3kqd6snd7p3gsxvm-source/src'
       > make: *** [Makefile:66: all] Error 2
       > make: Leaving directory '/build/3m8061y50vmda9cy3kqd6snd7p3gsxvm-source/src'
       For full logs, run 'nix log /nix/store/cn7wcxglfhz7lgn9igh473p26vvbmmjd-coq8.15-vellvm-dev.drv'.

**Comment by Chobbes** [comment]
Did you `git clone --recursive`? If not you can use `make update-submodules` to fetch the QuickChick submodule --- we're using a custom version, along with `flocq-quickchick`.

**Comment by ahmedshakill** [comment]
I used --recursive while clonning.
It still fails with the following error

COQC coq/Numeric/IEEE754_extra.v
File "./coq/Numeric/IEEE754_extra.v", line 35, characters 21-22:
Error: The reference Z was not found in the current environment.

make[2]: *** [Makefile:120: coq/Numeric/IEEE754_extra.vo] Error 1

**Comment by Chobbes** [comment]
Oh, you're using `nix build`. Flakes don't include submodules by default.

If you want to build from inside the repo, I'd recommend `cd`ing into `src/` and running `make` after getting a shell from `nix develop`. Otherwise you can do this when in the repo:

```
 nix build ".#?submodules=1"
```

Or if you just want to build the flake with a link:

```
 nix build "git+https://github.com/vellvm/vellvm?submodules=1" 
```

**Comment by ahmedshakill** [comment]
Not building with nix this time . 

Analyzing Coq dependencies
make coq
make[1]: Entering directory '/home/shakil/work/repos/vellvm/src'
make coq/Numeric/Archi.vo coq/Numeric/Coqlib.vo coq/Numeric/Integers.vo coq/Numeric/Zbits.vo coq/Numeric/IEEE754_extra.vo coq/Numeric/Floats.vo coq/Utils/ParserHelper.vo coq/Utils/Tactics.vo coq/Utils/Util.vo coq/Utils/AListFacts.vo coq/Utils/ListUtil.vo coq/Utils/Error.vo coq/Utils/PropT.vo coq/Utils/PostConditions.vo coq/Utils/TFor.vo coq/Utils/NoFailure.vo coq/Utilities.vo coq/Syntax/LLVMAst.vo coq/Syntax/AstLib.vo coq/Syntax/CFG.vo coq/Syntax/Traversal.vo coq/Syntax/DynamicTypes.vo coq/Syntax/TypToDtyp.vo coq/Syntax/Scope.vo coq/Syntax/SurfaceSyntax.vo coq/Syntax.vo coq/Semantics/MemoryAddress.vo coq/Semantics/DynamicValues.vo coq/Semantics/LLVMEvents.vo coq/Semantics/IntrinsicsDefinitions.vo coq/Handlers/Intrinsics.vo coq/Handlers/Local.vo coq/Handlers/Global.vo coq/Handlers/Stack.vo coq/Handlers/Pick.vo coq/Handlers/Memory.vo coq/Handlers/MemoryTheory.vo coq/Handlers/Handlers.vo coq/Semantics/Denotation.vo coq/Semantics/InterpretationStack.vo coq/Semantics/TopLevel.vo coq/Semantics.vo coq/Analysis/Iteration.vo coq/Analysis/Kildall.vo coq/Analysis/Dom.vo coq/Analysis/DomKildall.vo coq/Analysis/ssa.vo coq/Analysis/DomId.vo coq/Syntax/ScopeTheory.vo coq/Theory/StatePredicates.vo coq/Theory/Refinement.vo coq/Theory/InterpreterMCFG.vo coq/Theory/InterpreterCFG.vo coq/Theory/ExpLemmas.vo coq/Theory/InstrLemmas.vo coq/Theory/DenotationTheory.vo coq/Theory/LocalFrame.vo coq/Theory/TopLevelRefinements.vo coq/Theory/SymbolicInterpreter.vo coq/Utils/NoEvent.vo coq/Utils/Commutation.vo coq/Theory.vo coq/Transformations/Transform.vo coq/Transformations/EquivExpr.vo coq/Transformations/BlockFusion.vo coq/Transformations/DeadCodeElimination.vo
make[2]: Entering directory '/home/shakil/work/repos/vellvm/src'
make[2]: 'coq/Numeric/Archi.vo' is up to date.
make[2]: 'coq/Numeric/Coqlib.vo' is up to date.
make[2]: 'coq/Numeric/Integers.vo' is up to date.
make[2]: 'coq/Numeric/Zbits.vo' is up to date.
COQC coq/Numeric/IEEE754_extra.v
File "./coq/Numeric/IEEE754_extra.v", line 35, characters 21-22:
Error: The reference Z was not found in the current environment.

make[2]: *** [Makefile:120: coq/Numeric/IEEE754_extra.vo] Error 1
make[2]: Leaving directory '/home/shakil/work/repos/vellvm/src'
make[1]: *** [Makefile:78: coq] Error 2
make[1]: Leaving directory '/home/shakil/work/repos/vellvm/src'
make: *** [Makefile:66: all] Error 2

**Comment by ahmedshakill** [comment]
It is pointing to an error  in 

File "./coq/Numeric/IEEE754_extra.v", line 35, characters 21-22

which is this line in the file

_Variable prec emax : Z._

**Comment by Chobbes** [comment]
Are you using a `nix develop` shell, or did you ditch nix entirely? I'm pretty sure this problem occurs when you don't have the right versions of the libraries.

For what it's worth, I have personally confirmed that the `nix` build commands I have given work, as well as building with `make` after using the `nix develop .` shell.

Are you building the `dev` branch?

**Comment by ahmedshakill** [comment]
I am in dev branch  and not using nix at all now.

**Comment by Chobbes** [comment]
Then you are on your own :). If you do switch to the nix shell, remember to `make distclean`.

**Comment by ahmedshakill** [comment]
I'll let you know how it goes once I switch to nix again.

**Comment by Chobbes** [comment]
Closing for now, the nix build appears to work for me as long as you enable submodules.

**Comment by k4rtik** [comment]
@Chobbes I am on `dev` branch and not using nix, but I get the same error about `Z`:

```
❯ make
Analyzing Coq dependencies
make coq
make[1]: Entering directory '/Users/kartik/Hub/vellvm/src'
make coq/Numeric/Archi.vo coq/Numeric/Coqlib.vo coq/Numeric/Integers.vo coq/Numeric/Zbits.vo coq/Numeric/IEEE754_extra.vo coq/Numeric/Floats.vo coq/Utils/ParserHelper.vo coq/Utils/Tactics.vo coq/Utils/Util.vo coq/Utils/AListFacts.vo coq/Utils/ListUtil.vo coq/Utils/Error.vo coq/Utils/PropT.vo coq/Utils/PostConditions.vo coq/Utils/TFor.vo coq/Utils/NoFailure.vo coq/Utilities.vo coq/Syntax/LLVMAst.vo coq/Syntax/AstLib.vo coq/Syntax/CFG.vo coq/Syntax/Traversal.vo coq/Syntax/DynamicTypes.vo coq/Syntax/TypToDtyp.vo coq/Syntax/Scope.vo coq/Syntax/SurfaceSyntax.vo coq/Syntax.vo coq/Semantics/MemoryAddress.vo coq/Semantics/DynamicValues.vo coq/Semantics/LLVMEvents.vo coq/Semantics/IntrinsicsDefinitions.vo coq/Handlers/Intrinsics.vo coq/Handlers/Local.vo coq/Handlers/Global.vo coq/Handlers/Stack.vo coq/Handlers/Pick.vo coq/Handlers/Memory.vo coq/Handlers/MemoryTheory.vo coq/Handlers/Handlers.vo coq/Semantics/Denotation.vo coq/Semantics/InterpretationStack.vo coq/Semantics/TopLevel.vo coq/Semantics.vo coq/Analysis/Iteration.vo coq/Analysis/Kildall.vo coq/Analysis/Dom.vo coq/Analysis/DomKildall.vo coq/Analysis/ssa.vo coq/Analysis/DomId.vo coq/Syntax/ScopeTheory.vo coq/Theory/StatePredicates.vo coq/Theory/Refinement.vo coq/Theory/InterpreterMCFG.vo coq/Theory/InterpreterCFG.vo coq/Theory/ExpLemmas.vo coq/Theory/InstrLemmas.vo coq/Theory/DenotationTheory.vo coq/Theory/LocalFrame.vo coq/Theory/TopLevelRefinements.vo coq/Theory/SymbolicInterpreter.vo coq/Utils/NoEvent.vo coq/Utils/Commutation.vo coq/Theory.vo coq/Transformations/Transform.vo coq/Transformations/EquivExpr.vo coq/Transformations/BlockFusion.vo coq/Transformations/DeadCodeElimination.vo
make[2]: Entering directory '/Users/kartik/Hub/vellvm/src'
COQC coq/Numeric/Archi.v
COQC coq/Numeric/Coqlib.v
COQC coq/Numeric/Integers.v
COQC coq/Numeric/Zbits.v
COQC coq/Numeric/IEEE754_extra.v
File "./coq/Numeric/IEEE754_extra.v", line 35, characters 21-22:
Error: The reference Z was not found in the current environment.

make[2]: *** [Makefile:120: coq/Numeric/IEEE754_extra.vo] Error 1
make[2]: Leaving directory '/Users/kartik/Hub/vellvm/src'
make[1]: *** [Makefile:78: coq] Error 2
make[1]: Leaving directory '/Users/kartik/Hub/vellvm/src'
make: *** [Makefile:66: all] Error 2
```

---
EDIT: never mind the following, they are not reproducible.

On `make distclean`, I see some warnings, that may be helpful?
```
[...]
coq_makefile -f _CoqProject -o Makefile
Warning: ../QuickChick/src (used in -R or -Q) is not a subdirectory of the current directory

Warning: No common logical root.
Warning: In this case the -docroot option should be given.
Warning: Otherwise the install-doc target is going to install files
Warning: in orphan_QuickChick_FlocqQuickChick
CLEAN
[...]
```

**Comment by Chobbes** [comment]
@k4rtik I believe the `dev` branch might need flocq 3.4.3, so you probably have the wrong version.

**Comment by k4rtik** [comment]
Ah, that was certainly the issue. I installed the dependencies using `make opam` and it must have installed the most recent version. Removing that and using `opam install coq-flocq.3.4.3` fixed the problem. Thanks!
