### ISSUE TITLE
Proof of refine_undef in TopLevelRefinements.v

### ISSUE THREAD

**Issue by Chobbes** [vellvm/vellvm#331]
Looks like this lemma needs a proof:

```
    Lemma refine_undef
      : forall (E F:Type -> Type) T TT (HR: Reflexive TT)  `{UBE -< F} `{FailureE -< F} `{OOME -< F}
               (xs : PropT _ T),
        forall x, xs x -> model_undef TT xs (@exec_undef E F _ _ _ _ x).
```

This should be doable by somebody else.

The top level `interpreter_sound` lemma depends upon this lemma, so it is important.

**Comment by Zdancewic** [comment]
@euisuny I started to take a crack at this last night - it looks like your `raiseOOM_map_itree_inv` may be useful for this line of proofs.

**Comment by Chobbes** [comment]
This got Qed'd.
