### ISSUE TITLE
Seemingly conflicting poison results in v0.0

### ISSUE THREAD

**Issue by rsofaer** [vellvm/vellvm#355]
Hello,

I'm looking at vellvm while considering different formalizations of LLVM semantics for an upcoming project.  I'm trying to figure out the following example right now.  @add_vuln adds 10 to its input with add nsw and returns it, meaning it gives poison if given too large a number.  @add_patch should never give poison, and @add_wrong_patch should do the opposite of @add_patch.  Instead it looks like all three give poison, which I didn't expect.

Q1: Why does @add_patch give poison?
Q2: In general, is there any machinery for stepping through the reasoning about a program and exploring why the asserts are giving the result that they are giving?

Thank you!
Raphael

```
; ModuleID = 'Examples/code/add1.c'
source_filename = "Examples/code/add1.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; Function Attrs: noinline norecurse nounwind readnone uwtable
define i32 @add_vuln(i32 %n) #0 {
entry:
  %add = add nsw i32 %n, 10
  ret i32 %add
}

; Function Attrs: noinline norecurse nounwind readnone uwtable
define i32 @add_patch(i32 %n) #0 {
entry:
  %cmp = icmp sgt i32 %n, 2147483637
  %add = add nsw i32 %n, 10
  %retval.0 = select i1 %cmp, i32 2147483647, i32 %add
  ret i32 %retval.0
}
define i32 @add_wrong_patch(i32 %n) #0 {
entry:
  %cmp = icmp sle i32 %n, 2147483637
  %add = add nsw i32 %n, 10
  %retval.0 = select i1 %cmp, i32 2147483647, i32 %add
  ret i32 %retval.0
}

define i32 @main() {
entry:
    %retval = call i32 @add_patch(i32 2147483647)
    ret i32 %retval
}

; ASSERT EQ: i32 2147483647 = call i32 @add_patch(i32 2147483647)
; ASSERT POISON: call i32 @add_vuln(i32 2147483647)
; ASSERT POISON: call i32 @add_patch(i32 2147483647)
; ASSERT POISON: call i32 @add_wrong_patch(i32 2147483647)
```

```
(* -------- Vellvm Test Harness -------- *)

add1:
  failed - UVALUE_I32(2147483647) = add_patch(UVALUE_I32(2147483647))
	   ERROR: not equal
  passed - UVALUE_Poison = add_vuln(UVALUE_I32(2147483647))
  passed - UVALUE_Poison = add_patch(UVALUE_I32(2147483647))
  passed - UVALUE_Poison = add_wrong_patch(UVALUE_I32(2147483647))
(*-------------------------------------- *)
Passed: 3/4
Failed: 1/4
```

**Comment by Chobbes** [comment]
add_patch should return `%retval.0` instead of `%add` if you want to avoid `poison`? Same mistake in `add_wrong_patch`?

**Comment by rsofaer** [comment]
Sorry! I copied the code from mid experiment.  The results with `%retval.0` and `%add` are the same.

**Comment by rsofaer** [comment]
Never mind, I think I had a version mismatch and gave you a bad report!

**Comment by Chobbes** [comment]
In `@add_patch` the comparison is wrong, it would be false and would return `%add`, which is poison.

The other potential issue is that I believe in the v0.0 branch select is poison if either result is poison, which is more aggressive than it should be.

**Comment by rsofaer** [comment]
> The other potential issue is that I believe in the v0.0 branch select is poison if either result is poison, which is more aggressive than it should be.

Yes, that is definitely the reason, now that I look at `doc/intern/notes.org` I see that it says explicitly that if any operand of select is poison, the result is poison.

**Comment by rsofaer** [comment]
The current version of the LangRef says `Most instructions return ‘poison’ when one of their arguments is ‘poison’. A notable exception is the [select instruction](https://llvm.org/docs/LangRef.html#i-select). Propagation of poison can be stopped with the [freeze instruction](https://llvm.org/docs/LangRef.html#i-freeze).`, suggesting that select should only give poison if the selected operand is poison.

**Comment by rsofaer** [comment]
I see the structure has changed a lot in model_proof_test, but just modifying the semantics in v0.0 to remove that additional poisoning logic didn't cause any compilation/proof errors.  All the asserts I expected to pass now pass.  Thanks for your help and sorry to keep pinging you.

**Comment by Chobbes** [comment]
> The current version of the LangRef says `Most instructions return ‘poison’ when one of their arguments is ‘poison’. A notable exception is the [select instruction](https://llvm.org/docs/LangRef.html#i-select). Propagation of poison can be stopped with the [freeze instruction](https://llvm.org/docs/LangRef.html#i-freeze).`, suggesting that select should only give poison if the selected operand is poison.

Yep :). This is why this is fixed in the model-proof-test branch. I'm not certain the behavior in the dev branch was ever considered correct according to LangRef, but it's something from a long time ago and I think LangRef wasn't explicit about it. I was eagerly putting UB as many places as possible, and I think my thought process was that if any operand to an instruction was `poison` the result should be `poison` as well.

> Q2: In general, is there any machinery for stepping through the reasoning about a program and exploring why the asserts are giving the result that they are giving?

Also, I should probably answer this... Not really, no! The current development currently has an implementation for `puts` which could potentially be helpful, but I don't think this has been backported to the `dev` branch.
