### ISSUE TITLE
Brackets missing in printed AST

### ISSUE THREAD

**Issue by klausnat** [vellvm/vellvm#367]
Hello, 

I am trying to interpret an AST into an itree using the interpreter function from Semantics/TopLevel.v

When I am using -print-ast in command line, some brackets are missing  (see the image), so code does not type-check.

I tried several times and TLE_Definition is broken

![Bracket](https://github.com/vellvm/vellvm/assets/43129812/93d223dc-4292-4435-9c5b-7163860f9c3b)

**Comment by Chobbes** [comment]
@klausnat I believe I have fixed this issue in the [latest commit](https://github.com/vellvm/vellvm/commit/a87c76efc9e7620fa73b1458656a71ae28f0bf83). Just waiting on CI (and looks like the Coq docker image got deleted again...).

I'll try to make an opam release with this fix soon.

**Comment by Chobbes** [comment]
Should be fixed, and opam release has been made. Let me know if you still have problems!
