### ISSUE TITLE
dsss and master branches separation

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#4]
Currently, there are traces of DSSS code in the master branch which cause compilation problems. Imp, Vminus, QuickChick stuff. Since DSSS17 is using _dsss_ branch I think it is a good idea to remove all DSSS-related materials from _master_.

**Comment by Zdancewic** [comment]
Yes -- this is a relic from the run-up to the DSSS.  I've just excised all of the dsss material from the master branch and put it all in a new branch called imp_compiler.

**Comment by vzaliva** [comment]
Thanks! I just tested and it compiles without problem.
