### ISSUE TITLE
ExceptionMonad is lawless, add laws?

### ISSUE THREAD

**Issue by bollu** [vellvm/vellvm#42]
The current definition of [`ExceptionMonad`](https://github.com/vellvm/vellvm/blob/8ba75559303f1cf28b5466c17640c2e4574a0aa5/src/coq/Classes.v#L422) has no laws associated to this theory. I would have excepted to find a law:

```coq
raise e >>= f ≡ raise e.
```

to reason about error propagation.

Will there be the functionality of `catchError` as provided by [`MonadError`](http://hackage.haskell.org/package/mtl-2.2.2/docs/Control-Monad-Except.html)?

In that case, we would need another law:

```hs
catchError (raise e) f ≡ f  e
```
This blog post mentions one more rule about the interaction between [`ret` and catching](https://lukajcb.github.io/blog/functional/2018/04/15/rethinking-monaderror.html).

Unfortunately, I can't find an authoritative source on laws off-hand.

**Comment by YaZko** [comment]
Hello Siddharth,

I just discussed the question with Steve, the ExceptionMonad is at the moment minimalist given we only really use it as an Error monad, and might in the future move toward a third party monad library. 

PR #44 should however fit your need. Let me know if you had other laws in mind.
