### ISSUE TITLE
Semantics of jump are tied up with instructions in the new basic block

### ISSUE THREAD

**Issue by bollu** [vellvm/vellvm#43]
Taking a look at the definition of [`jump`](https://github.com/vellvm/vellvm/blob/8ba75559303f1cf28b5466c17640c2e4574a0aa5/src/coq/StepSemantics.v#L422):

##### `jump`
```coq
Definition jump (fid:function_id) (bid_src:block_id) (bid_tgt:block_id) (g:genv) (e_init:env) (k:stack) : Trace result :=
  let eval_phi (e:env) '(iid, Phi t ls) :=
      match assoc RawIDOrd.eq_dec bid_src ls with
      | Some op =>
        let dt := eval_typ t in
        'dv <- eval_exp g e_init (Some dt) op;
          mret (add_env iid dv e)
      | None => failwith ("jump: block " ++ string_of bid_src ++ " not found in " ++ string_of iid)
      end
  in
  match find_block_entry CFG fid bid_tgt with
  | None => raise ("jump: target block " ++ string_of bid_tgt ++ " not found")
  | Some (BlockEntry phis pc_entry) =>
      'e_out <- monad_fold_right eval_phi phis e_init;
      cont (g, pc_entry, e_out, k)
  end.
```

We observe that `jump` relies on [`find_block_entry`](https://github.com/vellvm/vellvm/blob/bfcae7ef626ef618805be1b4ba3ed8c5e6d57825/src/coq/CFG.v#L143) to find the jump target. 

##### `find_block_entry`
```coq
Definition fallthrough (cd: code) term_id : instr_id :=
  match cd with
  | [] => term_id
  | (next, _)::_ => next
  end.

..
Definition blk_entry_id (b:block) : instr_id := fallthrough (blk_code b) (blk_term_id b). 
...

Definition blk_entry_pc (fid:function_id) (b:block) :=
  mk_pc fid (blk_id b) (blk_entry_id b).

...

Definition block_to_entry (fid:function_id) (b:block) : block_entry :=
  BlockEntry (blk_phis b) (blk_entry_pc fid b).

Definition find_block_entry (CFG:mcfg) (fid:function_id) (bid:block_id) : option block_entry :=
  'cfg <- find_function CFG fid;
  'blk <- find_block (blks (df_instrs cfg)) bid;
  mret (block_to_entry fid blk).  
```
The calls of interest to us are:
1.  `find_block_entry` 
2.  `block_to_entry`
3.  `blk_entry_pc`
4. `blk_entry_id`
5. `fallthrough`

`fallthrough` is problematic, because it defines the semantics in terms of the IDs of the _instructions in the basic block_, _not_ the basic block.

So, all of the transforms listed below will change `fallthrough`, which changes `jump` and `find_block_entry`, while intuitively, they are not changing control flow:

1. remove a _dead instruction_ at the top of the BB
2. Add a `phi` / remove a `phi`
3. Change the _label_ of the first instruction in a basic block
4.  In general, _anything_ that touches the __first instruction's name__ will inhibit us from proving the fact:

 ```coq
Lemma control_flow_unchanged: find_block_entry CFG fn block =
 find_block_entry (rewrite_cfg CFG) (rewrite_fn fn) (rewrite_block blk)
```

I find this state of affairs somewhat dissatisfying, because I am trying to prove a pass where I switch the ordering of stores in a basic block. However, if I swap the first and second instruction in the basic block, the `instr_id`  of the first instruction in a BB will obviously change, and thus I can't prove preservation of `find_block_entry`.

It would be great if we somehow separate out the notion of "control flow" from "execution".

**Comment by Zdancewic** [comment]
I agree that the old version is not ideal in this regard.  As an experiment, I created a new branch called "better_pc" (not at all tested yet) that replaces the instruction id component of the pc with a natural number.  The offset must be 0 < offs <= List.length (blk_code b).   The pc of the terminator is exactly when the offset is equal to the length of the instructions, otherwise it's just used as a List.nth.

If you can try this version with your proofs, I think it would make sense to merge it into master after a bit of testing.

**Comment by Zdancewic** [comment]
This issue is obsolete -- the new ITrees semantics should side step all of these anti-modular dependencies.
