### ISSUE TITLE
Canonical structures versus typeclasses?

### ISSUE THREAD

**Issue by bollu** [vellvm/vellvm#47]
I was looking up the differences between the two approaches recently, and I do not clearly understand the choice between these two. However, there seems to be general agreement that canonical structures "scale" better in terms of performance. 

Consult [this issue against `coq/coq`](https://github.com/coq/coq/issues/7788) for some of the discussion that occured.

In light of this, I was wondering about the choice between canonical structures and typeclasses in `vellvm`.

**Comment by YaZko** [comment]
Steve is the one to know the history in the case of Vellvm naturally. 

However in most cases, the answer to this question is purely cultural/historical. Both mechanisms address essentially the same issue. Canonical Structures were introduced by Georges Gonthier and all his coworkers as part of the formalization of the Feit-Thomson theorem. In parallel, type classes were introduced by Mathieu Sozeau as part of the "official" coq development. So in practice, and while we should obviously go beyond that, type classes tend to be used by default, while canonical structures tend to be used in developments led by former member of Gonthier's team.

To get back to Vellvm, a closer inspection could be a good idea, but I do not think performances are an issue in any case. Their use is extremely light, pretty much only to allow monadic programming. Performances tend to be an issue when you start nesting them, typically to manipulate increasingly rich structured sets, or if you use them for non-trivial proof search.

**Comment by bollu** [comment]
I see, cool, thanks for the information :) I was curious about the choice of decision, and the argument about the usage being "light" convinces me. Thanks!
