### ISSUE TITLE
RFC: Proposal for tiered execution model of the interpreter

### ISSUE THREAD

**Issue by bollu** [vellvm/vellvm#49]
I've been playing around with refactoring `StepSemantics` to become a "tiered" execution model.

That is, rather than having one `exec` function which executes instruction by instruction, and we define the semantics of our LLVM program with respect to this.

I propose a way to try and split this `exec` function into a tiered execution model, such that we have `exec, `exec_function`, exec_block`, `exec_inst`, and we transfer control flow between these different `exec_*` functions.

##### Documentation of new implementation
[Link to `coq2html` documentation of implementation, which I will keep updating as this discussion evolves.](https://bollu.github.io/vellvm/src/doc/html/StepSemanticsTiered.html)

[Link to implementation](https://github.com/bollu/vellvm/blob/de9338559c703f271d3efaeb69a9a9cafc388f92/src/coq/StepSemanticsTiered.v)

##### Links
This implementation also uses the `better_pc` representation: That is, instructions and control flow is tracked with respect to a natural number, rather than the instruction ID. Reference issue #43, [`better_pc` branch](https://github.com/vellvm/vellvm/tree/better_pc)

**Comment by Zdancewic** [comment]
In our "Legacy Vellvm" development, we had similar functionality for "big-stepping" past blocks or through function calls.  We implemented those large step semantics on top of the small-step semantics by writing helper functions that called out to the small steps and then proving theorems that related them. 

 I'll take a closer look at your proposal in the next day or two.   Thanks!

**Comment by bollu** [comment]
Yes, please do, and feel free to ask about extensions you'd like to see / issues. I'd love to stress test this against some tricky examples, if you have some cases like that It'd be cool to hear.

So far, it's served me well.

**Comment by bollu** [comment]
Also, some links to the legacy definitions would be greatly appreciated

**Comment by Zdancewic** [comment]
The old legacy Vellvm code lives here:  (But it is pretty bit-rotted and quite ugly....)

https://github.com/vellvm/vellvm-legacy/tree/master/src/Vellvm
