### ISSUE TITLE
Suggestion: use coq-paco opam package

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#5]
Current build instructions require manual download and compilation of _paco_ library. I noticed it is available via OPAM as _coq-paco_ package. Installing it via OPAM will simplify VELLVM initial configuration.

The only problem is that OPAM paco package makes it available under _Paco_ prefix. I have not been able to figure out how to invoke tactics from it.

**Comment by vzaliva** [comment]
I did some investigation and it turns out coq-paco package holds older version of the library (1.0 vs 1.2.8).
I've sent them pull request to update it: https://github.com/coq-contribs/paco/pull/1 ). Once approved we can switch to opam-provided version.

**Comment by vzaliva** [comment]
Currently being worked on as part of the following issue: https://github.com/coq/opam-coq-archive/pull/219

**Comment by lastland** [comment]
Similarly, there is also an OPAM package for CompCert (`coq-compcert`).

**Comment by Zdancewic** [comment]
Last I checked, the OPAM package for CompCert did not support Coq 8.7.1 -- has that changed yet?

**Comment by lastland** [comment]
It has. The 3.2.0 version supports Coq 8.7.1.

Though it has not supported 8.7.2 yet.

**Comment by Zdancewic** [comment]
We decided to stick with submodules for this rather than OPAM.
