### ISSUE TITLE
A way to commute `memD` with `bindM`: proof strategy for composable proofs of passes

### ISSUE THREAD

**Issue by bollu** [vellvm/vellvm#50]
This is an open-ended issue regarding how to compose proofs together in the `Trace` model. Any references would be appreciated.

The question is this: How does one write compositional proofs when dealing with semantics with respect to traces? 

Assume I wish to prove a lemma:
```coq
Theorem basic_block_preservation_implies_semantic_preservation:
  forall (pass: block -> block),
 preserves_block_semantics pass -> preserves_program_semantics (lift pass)
```

for some appropriate choice of `preserves_block_semantics` and `preserves_program_semantics`.

`preserves_program_semantics` appears to be easy:
```coq
Definition preserves_program_semantics (pass: mcfg -> mcfg): Prop :=
forall (MCFG: mcfg), memD (TopLevel.run_program_with_memory (pass MCFG)) = 
memD (TopLevel.run_program_with_memory (MCFG)
```
That is, a pass preserves program semantics if after interpretation by the memory model, the traces are equal (or equivalent, if we want to). (I hope we all agree till this point?)

Now, the issue at hand is the definition of `preserves_block_semantics`.
Do we choose to define it the same way?
```coq
Definition preserves_block_semantics_1 (pass: block -> block): Prop :=
forall (blk: block), memD (exec_block (pass blk) <other params>) =
memD (exec_block blk <other params>)
```

This can be defined by using the `exec_block` as proposed in the [tiered execution model](https://github.com/vellvm/vellvm/issues/49).

Assume we choose this definition. Now, given this definition, what do we need to show `preserves_program_semantics`? I believe we need some way to reason about the "gluing" together of traces.

Intuitively, the semantics of our program is defined by "gluing" / "growing" the free(er) monad (`M E X`) by sequencing operations with `>>=`. So, we need some sort of theorem that will let us reason about objects like:
```coq
memD (x >>= f >>= g >>= ...)
```

since that is what our entire program looks like (where `f`, `g`, etc for example compose basic blocks together).

I have a partial theorem in this direction proved in this direction, [`memD_commutes_with_bind`](https://github.com/bollu/vellvm/blob/7bb65de819ca0b97bafb81c7b01754fa23d9e001/src/coq/Memory.v#L628), whose statement is:

```coq
(** TraceFinite observes that a trace is finite, defined in Trace.v **)
Inductive TraceFinite {E: Type -> Type} {X: Type}: M E X -> Type :=
| TFRet: forall (x: X), TraceFinite (Ret x)
| TFErr: forall (s: String.string), TraceFinite (Err s)
| TFTau: forall (mex: M E X) (FIN: TraceFinite mex),
    TraceFinite (Tau mex)
| TFVis: forall {Y: Type} (e: E Y) (k: Y -> M E X)
           (FINK: forall (y: Y), TraceFinite (k y)),
TraceFinite (Vis e k)

(** Tear down the finite trace to record effects that happened on memory **)
Fixpoint mem_effect {X} (m: memory) (d: Trace X) (FIN: Trace.TraceFinite d)
{struct FIN}: memory *Trace X := ...

(** THEOREM OF INTEREST *)
(** It allows us to observe the effect the x had on m, to produce m' and trx'
which are used to create the rest of the trace *)
Theorem memD_commutes_with_bind: forall {X Y: Type}
                                 (trx: Trace X)
                                 (FINTRX: Trace.TraceFinite trx)
                                 (f: X -> Trace Y)
                                 (m: memory),
    let (m', trx') := mem_effect m FINTRX
    in memD m (bindM trx f) ≡
memD m' (bindM trx' f).
Proof
...
Qed
(** The proof checks out *)
```

So, roughly, `mem_effect` tears down the witness `FINTRX` to run the effects on memory and produce the final state,  which can be used to "factor" `memD` through a `>>=`.

With this tool, we should be able to show the above theorem, with the rough proof strategy being that:
1. the basic block preserves `memD`, which means it preserves the state of memory as observed by `memEffect`
2. Since the entire program contains basic block executions (plus other things which we will assume are preserved),  we "step through" the execution, rewriting `memD` into `memEffect`, showing that the memory states are equal at every basic block execution between the old program and the new program. 

Without such a tool at hand, I am unsure how to prove semantic preservation.

So, questions:
1. Do you believe this `mem_effect` is useful? If not, what is a better proof strategy?
2. Currently, `mem_effect` can only work on finite traces. can this be extended to infinite traces?
3. `TraceFinite` lives in `Type` (because `mem_effect` needs to destructure on `TraceFinite`. However, it "feels" like an object that must live in `Prop`. Do you have any suggestions about this?
4. In general, what is your view on structuring proofs of semantic preservation of "larger chunks" of IR such as functions, basic blocks, etc.
5. Another proof strategy I had considered was to show a relationship in the traces produced between the original `p` and the new `pass p`, and then use this to show that when running the traces, the `memD` effect is the same. However, this is super unwieldy because the `Trace` is quite painful to write out explicitly (especially when it comes to `Vis` nodes), so I have not succeeded with this proof strategy. Do you have any suggestions regarding this?

Thanks a lot!

**Comment by bollu** [comment]
I have a partial solution, which disallows external function calls in the trace, to construct this `mem_effect` function. [Solution logged here](https://github.com/bollu/vellvm/commit/69f2118be94aee7e8079b4520d8dfc0c0e99f48e)

A copy of the commit message because I tend to destroy history sometimes:
 
#### Destroy our memory model to give up on external function calls.

This is useful since we can now talk about enriching traces with the
value of memory. That is, we can write a function:
```coq
mem_effect: Mem -> Trace X -> Trace (Memory * X)
```
where the leaf nodes are enriched with the state of memory at that
point. The downside is that our memory model gives up when there is an
external function call and returns am "Err"

The less destructive path would have been to have a coinductive
predicate (in `Prop`) `TraceDoesNotContainExternalFunctionCall`
that the trace does not contain external function
calls. So we would write a function:
```coq
mem_effect: Mem -> (x: Trace X)
                -> TraceDoesNotContainExternalFunctionCall x
                -> Trace (Memory * X)
```
However, Tobias had a convincing argument that this extra proof
engineering is not worth the effort, which I agree with. We can amend
this later if need be.

This is nice, because we can now talk about memory effects on infinite
traces without having to provide an explicit witness (in `Type`) about the
finiteness of the trace.

**Comment by Zdancewic** [comment]
Sorry for the lack of responsiveness!  (In the last two weeks, I was attending a meeting in California, then PLDI, then moving to Portland to work at Galois for the summer... :-)  Things should settle down for a little while now, so I'll have more time to work on Vellvm) 

Theorems that show that memD and bind commute (or something along those lines) will definitely be necessary.  One question is whether memD, as currently written, is really what we want.  I think that we  need a more general version that exposes the continuation partway through evaluating the memory model, something like the mem_effect that you proposed above.  I'd like to see if we can do that without giving up on external calls.

**Comment by bollu** [comment]
No worries regarding the delay!

So, I thought about this to some degree, and I am not sure if there is a way to expose the state of memory after an external call (the way `mem_effect` tries to do).

In fact, what are the semantics of an external call with respect to `vellvm`? CompCert uses [`extcall_sem`](http://compcert.inria.fr/doc/html/Events.html#extcall_sem) to tell us exactly what we know about memory after an external call.

I can't think of a reasonable way to commute `bindM` with `memD` in the presence of an external function call, because `memEffect` relies on _exposing_ the state of memory, which is impossible when one has a call that we know nothing about.

So, I have a `memD` `memEffect` implementations that perform the exposing as proposed, [with all the required commuting relations](https://bollu.github.io/vellvm/src/doc/html/Memory.html). This enables modular reasoning of semantics, such as: 
- [instruction preservation implies BB preservation](https://github.com/bollu/vellvm/blob/c5b5c7d9a332929fea52568af10f16ce847bd173/src/coq/Pass.v#L895)
- [effect of a single `store` instruction](https://github.com/bollu/vellvm/blob/master/src/coq/LoopReversalManualProof.v#L307)
- [effect of a single basic block](https://github.com/bollu/vellvm/blob/master/src/coq/LoopReversalManualProof.v#L343)


etc. I'm very happy with the shape of the current `master` I have, which implements a way to expose the intermediate memory state + a refined, multi-tiered model of execution.

We should probably discuss this in longer form sometime this week or the next? :)
