### ISSUE TITLE
Setup CI?

### ISSUE THREAD

**Issue by bollu** [vellvm/vellvm#55]
I see there is already a [travis branch](https://github.com/vellvm/vellvm/tree/travis). Could this be merged? That would help validate all pulls.

**Comment by Chobbes** [comment]
In theory, anyway. I am bad at travis. Currently it fails because part of the build can not find Menhir (but it works anyway... WHATEVER).

And currently it doesn't fail when it should because the test runner returns 0 even if tests fail.

**Comment by bollu** [comment]
OK, in that case, may I spend some time tonight fixing this and send a PR?
