### ISSUE TITLE
Enable Travis for vellvm/vellvm

### ISSUE THREAD

**Issue by bollu** [vellvm/vellvm#59]
Travis needs to be enabled on the travis webpage [as described here](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI).

Please enable this for `vellvm/vellvm` (I don't have access to the repo) so that we can get CI up and running :)

**Comment by Zdancewic** [comment]
This is done, and my test push is currently building on Travis.

**Comment by bollu** [comment]
thanks

**Comment by bollu** [comment]
@Zdancewic Unfortunately, I'm not able to view the travis CI information on the website:

 https://travis-ci.org/vellvm/vellvm.

On the other hand, here is what it looks like for a repo I _can_ see: 

https://travis-ci.org/coq/coq


Are you able to view CI information on an incognito / private tab?

**Comment by Zdancewic** [comment]
What's the difference between travis-ci.com and travis-ci.org?   It seems that somehow travis is set up (and running) here:  https://travis-ci.com/vellvm/vellvm  but there is a similar page here https://travis-ci.org/vellvm/vellvm.

I can see both in incognito mode.

**Comment by bollu** [comment]
Wow, good catch. I can see it on:
https://travis-ci.com/vellvm/vellvm

But __not__ on
https://travis-ci.org/vellvm/vellvm

But whatever, I assume this is just some travis CI bug :)

Thanks!

**Comment by Zdancewic** [comment]
Now I'm seeing the information at both sites.
