### ISSUE TITLE
Figure out how to cache Travis Compilation

### ISSUE THREAD

**Issue by Zdancewic** [vellvm/vellvm#61]
This setup from the hs-to-coq project might be relevant:

https://github.com/antalsz/hs-to-coq/blob/master/.travis.yml

**Comment by Chobbes** [comment]
We no longer use travis (it was murdered)...

But we now have CI through github actions, and the builds are cached using nix + cachix.

https://github.com/vellvm/vellvm/actions
https://github.com/vellvm/vellvm/issues/251
https://github.com/vellvm/vellvm/blob/finite-memory/nix.org#cachix
