### ISSUE TITLE
Flocq/IEEE754/Binary.vo) makes inconsistent assumptions over library Coq.Init.Notations

### ISSUE THREAD

**Issue by geandwor** [vellvm/vellvm#69]
try to install the vellvm.
coq : 8.8.0
Floqc: 3.3.0
ocaml: 4.07.0
system: mac OS Sierra.

installed  Floqc from source using make.

when make in the vellvm/src, terminal gives error 
Flocq/IEEE754/Binary.vo) makes inconsistent assumptions over library Coq.Init.Notations.

Any one knows how to fix this.

**Comment by vzaliva** [comment]
if there is a reason why you install Flocq from source, not via OPAM?
It looks like your Flocq was compiled with different version of Coq. If you upgraded Coq, you need to recompile it.

I recommend to use OPAM (per README.md) to install all dependencies.

**Comment by geandwor** [comment]
Thanks for your reply. 
I compile dependencies all under the same version of coq.
I had some problem using OPAM to install coq-floqc. That's why I installed floqc from source.
I got error when using OPAM:
[ERROR] The compilation of coq-flocq failed at
        "/Users/grandwor/.opam/opam-init/hooks/sandbox.sh build ./remake -j7".

#=== ERROR while compiling coq-flocq.3.0.0 ====================================#
# context     2.0.0 | macos/x86_64 | ocaml-system.4.07.0 | https://coq.inria.fr/opam/released
# path        ~/.opam/default/.opam-switch/build/coq-flocq.3.0.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./remake -j7
# exit-code   1
# env-file    ~/.opam/log/coq-flocq-12570-05296d.env
# output-file ~/.opam/log/coq-flocq-12570-05296d.out
### output ###
# Failed to create server: Operation not permitted.

**Comment by vzaliva** [comment]
Please see at the bottom of README about coq-flocq installation via OPAM.

**Comment by geandwor** [comment]
Thanks. It is fixed.
