### ISSUE TITLE
Proposal: comments in AST

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#71]
When generating IR code via Vellvm AST it could be very useful to be able to include comments. Such comments will not affect semantics but will be passed through to pretty-printed IR code. It will make generated code much more readable and easy to debug.

I can implement such an extension, but before doing so would like to check if there are any objections or thoughts on this.

**Comment by Zdancewic** [comment]
This is a good idea.  I don't think that it will be too hard to add this feature.  We will want to make sure that doing so doesn't add too much overhead to proofs, but that should be pretty easy by ignoring the comments for the purposes of the semantics.

**Comment by vzaliva** [comment]
merged
