### ISSUE TITLE
does not build with coq-8.9

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#91]
```
COQC theories/Eq/Eq.v
File "./theories/Eq/UpToTaus.v", line 69, characters 31-35:
Error: The reference cpn2 was not found in the current environment.
```

**Comment by Zdancewic** [comment]
This is a paco version problem for compiling the InteractionTrees library.  You should be good with coq-paco-2.1

**Comment by vzaliva** [comment]
I will try to pin an older version of paco. I was trying to use one provided by Opam for Coq-8.9 by default.
