### ISSUE TITLE
Depenency on `R` in ML code extraction

### ISSUE THREAD

**Issue by vzaliva** [vellvm/vellvm#98]
I was trying to debug some of our ML library code and wanted to do this interactively. This fails:

```
$ pwd                                                       
/home/lord/coq/vellvm/src/ml

~/c/v/s/ml (master|✔) $ dune utop                                              
Fatal error: exception Failure("AXIOM TO BE REALIZED")
Raised at file "stdlib.ml", line 33, characters 22-33
Called from file "extracted/Rdefinitions.ml", line 8, characters 2-33
```

It could be an indication of a bigger problem where we attempting to use some axioms in computations.

**Comment by vzaliva** [comment]
From this thread: https://discuss.ocaml.org/t/debugging-dune-utop/3773/5

The problem was caused by the following extracted code:

```
let coq_R0 =
  failwith "AXIOM TO BE REALIZED"
```
The exception is raised as a module loading side effect.
We need to see if we really need to extract Raxioms.

**Comment by vzaliva** [comment]
Lookin at it further, I see in Exract.v the following code:

```
(* Cutting the dependency to R. *)
Extract Inlined Constant Flocq.Core.Defs.F2R => "(fun _ -> assert false)".
Extract Inlined Constant Flocq.IEEE754.Binary.FF2R => "(fun _ -> assert false)".
Extract Inlined Constant Flocq.IEEE754.Binary.B2R => "(fun _ -> assert false)".
Extract Inlined Constant Flocq.IEEE754.Binary.round_mode => "(fun _ -> assert false)".
Extract Inlined Constant Flocq.Calc.Bracket.inbetween_loc => "(fun _ -> assert false)".
```

It looks like we missed some definitons there which tie us up to `R`. I wonder if there is an easy way to fo found in Vellvm code functions introducing such dependencies. @Zdancewic how you did this in the first place?

**Comment by Zdancewic** [comment]
I believe that the "cutting the dependency to R" stuff was adapted from CompCert at some point.  I'm not sure whether there is an easy way to determine the dependencies.

**Comment by YaZko** [comment]
This has been fixed some time ago, don't hesitate to reopen an issue if there are still problems at extraction but I'd be surprised.
